### PR TITLE
redesigned index.html page

### PR DESCRIPTION
**Pull request by teyim**
redesigned the main page of the application giving it a responsive and modern look and feel.

### CODE REVIEW

**Comment by nikunjdk** [comment]
Hey, the design is cool but whenever I type something the size of the box increases and decreases continuously. Can you tell me why?

**Comment by teyim** [comment]
i can work on that.i have also noticed that the welcome text and image are not centered.i can fix that as well

**Comment by nikunjdk** [comment]
that will be great. please do that

**Comment by nikunjdk** [comment]
that will be great. please do that

**Pull request merged**
